nameOverride: ""
fullnameOverride: ""

# Bitwarden configuration, these will be set when starting bitwarden_rs
bitwarden:
  # signups_allowed: true
  # invitations_allowed: true
  # server_admin_email: admin@example.com

  # TODO: Not supported currently
  # websocket_enabled: false

  # domain: https://bw.domain.tld

  # yubico_client_id: YUBICO_CLIENT_ID
  # yubico_secret_key: YUBICO_SECRET_KEY

  # rocket_limits: "{json=10485760}"
  # rocket_workers: 10
  # TODO: Cannot be changed currently
  rocket_port: 80 
  
  # smtp_host: smtp.domain.tld
  # smtp_from: bitwarden@domain.tld
  # smtp_port: 587
  # smtp_sll: true
  # smtp_username: username
  # smtp_password: password

  show_password_hints: false
  web_vault_enabled: true
  # TODO: web-vault path

  # log_file=/data/bitwarden.log

deployment:
  image:
    repository: mprasil/bitwarden
    tag: 1.5.0
    pullPolicy: IfNotPresent
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

service:
  type: ClusterIP
  port: 80

# TODO: Support DATABASE_URL + ATTACHMENTS_FOLDER + ICON_CACHE_FOLDER

# Data folder
storage:
  enabled: true
  path: "/bw-data"
  size: 100Mi

# Backup folder
backup:
  enabled: true
  path: "/bw-backup"
  size: 100Mi

  schedule: "*/1 * * * *"

  # Name the backup backup.sqlite3[TIMESTAMP] instead of backup.sqlite3
  timestamp: false
  # Create a file containing the timestamp of the backup
  timestamp_file: "/bw-backup/timestamp"

  image:
    repository: skeen/bitwarden_rs_backup
    tag: latest
    pullPolicy: Always

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ssl-redirect: "true"
  paths:
    - '/'
  hosts:
    - bitwarden.domain.tld  # host
  tls:
    - secretName: bitwarden-tls-secret
      hosts:
        - bitwarden.domain.tld  # host


